#!/usr/bin/env python3
"""arXiv PDF downloader for CiteBot.

Parses a .jsonl file generated by download_corpus.py, extracts the arXiv ID,
downloads the corresponding PDF, and converts it to text for CiteBot ingestion.

Requirements:
    pip install pymupdf requests
"""

import json
import logging
import os
import sys
import time
from pathlib import Path

import requests

try:
    import fitz  # PyMuPDF
except ImportError:
    print("Error: PyMuPDF not found. Please run: pip install pymupdf")
    sys.exit(1)

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s"
)
log = logging.getLogger("arxiv-pdf-downloader")


def download_pdf(arxiv_uri: str, output_path: Path) -> bool:
    """Download PDF from arXiv given a source URI."""
    # Convert http://arxiv.org/abs/2304.01234v1 to https://arxiv.org/pdf/2304.01234v1.pdf
    pdf_url = arxiv_uri.replace("/abs/", "/pdf/") + ".pdf"

    try:
        response = requests.get(pdf_url, timeout=30)
        response.raise_for_status()
        output_path.write_bytes(response.content)
        return True
    except Exception as e:
        log.error(f"Failed to download {pdf_url}: {e}")
        return False


def extract_text_from_pdf(pdf_path: Path) -> str:
    """Extract text content from a PDF file using PyMuPDF."""
    text = ""
    try:
        with fitz.open(str(pdf_path)) as doc:
            for page in doc:
                text += page.get_text()
    except Exception as e:
        log.error(f"Failed to extract text from {pdf_path}: {e}")
    return text


def main():
    import argparse

    parser = argparse.ArgumentParser(
        description="Download and parse PDFs from arXiv JSONL."
    )
    parser.add_argument("input_jsonl", type=Path, help="Path to arxiv_papers.jsonl")
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("data/full_text_corpus"),
        help="Where to save text documents",
    )
    parser.add_argument(
        "--max-docs", type=int, default=10, help="Max documents to process"
    )
    parser.add_argument(
        "--delay",
        type=float,
        default=3.0,
        help="Delay between downloads to respect arXiv ToS",
    )

    args = parser.parse_args()

    if not args.input_jsonl.exists():
        log.error(f"Input file not found: {args.input_jsonl}")
        return

    args.output_dir.mkdir(parents=True, exist_ok=True)
    pdf_temp_dir = args.output_dir / "temp_pdfs"
    pdf_temp_dir.mkdir(exist_ok=True)

    processed = 0
    with open(args.input_jsonl, "r") as f:
        for line in f:
            if processed >= args.max_docs:
                break

            doc = json.loads(line)
            source_uri = doc.get("source_uri")
            title = doc.get("title")

            if not source_uri or "arxiv.org" not in source_uri:
                continue

            arxiv_id = source_uri.split("/")[-1]
            pdf_path = pdf_temp_dir / f"{arxiv_id}.pdf"
            output_file = args.output_dir / f"{arxiv_id}.json"

            if output_file.exists():
                log.info(f"Skipping {arxiv_id}, already exists.")
                processed += 1
                continue

            log.info(f"Processing {arxiv_id}: {title}")

            if download_pdf(source_uri, pdf_path):
                text = extract_text_from_pdf(pdf_path)
                if text:
                    # Maintain CiteBot metadata structure
                    doc["text"] = text
                    doc["metadata"]["full_text_extracted"] = True

                    with open(output_file, "w") as out:
                        json.dump(doc, out)

                    log.info(f"Successfully processed {arxiv_id}")
                    processed += 1
                    time.sleep(args.delay)

                # Cleanup PDF to save space
                if pdf_path.exists():
                    pdf_path.unlink()

    log.info(f"Finished. Processed {processed} documents.")
    log.info(
        f"You can now ingest them using: python -m app.ingestion.cli ingest {args.output_dir}"
    )


if __name__ == "__main__":
    main()
    main()
