const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={sessionId:null,documents:[],jobs:[],citations:[],busy:false};
const api={
  headers(scope,json=true){const h={};const key=localStorage.getItem(scope==='admin'?'citebot.adminKey':'citebot.researchKey');if(key)h['X-Api-Key']=key;if(json)h['Content-Type']='application/json';return h},
  async request(path,options={}){const response=await fetch(`/api/v1${path}`,options);if(!response.ok){let detail=`Request failed (${response.status})`;try{detail=(await response.json()).detail||detail}catch{}throw new Error(detail)}return response.status===204?null:response.json()}
};
function showView(name){$('#chatView').classList.toggle('hidden',name!=='chat');$('#documentsView').classList.toggle('hidden',name!=='documents');$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='documents')refreshDocuments()}
function toast(message,error=false){const el=document.createElement('div');el.className=`toast${error?' error':''}`;el.textContent=message;$('#toastRegion').append(el);setTimeout(()=>el.remove(),4200)}
function escapeHtml(text=''){return text.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function formatDate(value){return new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',year:'numeric'}).format(new Date(value))}
function bytes(value){if(value==null)return '';if(value<1024)return `${value} B`;if(value<1048576)return `${(value/1024).toFixed(1)} KB`;return `${(value/1048576).toFixed(1)} MB`}
async function refreshDocuments(){try{const [documents,jobs]=await Promise.all([api.request('/documents',{headers:api.headers('admin',false)}),api.request('/documents/jobs',{headers:api.headers('admin',false)})]);state.documents=documents;state.jobs=jobs;renderDocuments();$('#libraryHint').textContent(`${documents.length} source${documents.length===1?'':'s'} ready`)}catch(error){$('#libraryHint').textContent='Library unavailable';toast(error.message,true)}}
function renderDocuments(){const query=$('#documentSearch').value.toLowerCase();const docs=state.documents.filter(d=>d.title.toLowerCase().includes(query));const pending=state.jobs.filter(j=>['queued','running'].includes(j.status));$('#documentCount').textContent=`${state.documents.length+pending.length} document${state.documents.length+pending.length===1?'':'s'}`;$('#readyCount').textContent=`${state.documents.length} ready`;const pendingRows=pending.map(j=>documentRow({title:j.source_path.split('/').pop(),source_uri:j.source_path,ingested_at:j.started_at,chunk_count:'—'},'processing',j.stage||j.status));const docRows=docs.map(d=>documentRow(d,'ready','Ready'));$('#documentList').innerHTML=[...pendingRows,...docRows].join('')||'<div class="document-row"><span>No documents yet. Add your first source above.</span></div>'}
function documentRow(doc,status,label){const ext=(doc.title.split('.').pop()||'DOC').slice(0,4).toUpperCase();return `<div class="document-row" role="row"><span class="document-name"><i class="file-glyph">${escapeHtml(ext)}</i><span><strong>${escapeHtml(doc.title)}</strong><small>${escapeHtml(bytes(doc.size_bytes)||doc.source_uri)}</small></span></span><span class="status ${status}">${escapeHtml(label)}</span><span>${formatDate(doc.ingested_at)}</span><span>${doc.chunk_count}</span></div>`}
async function uploadFiles(files){for(const file of files){toast(`Uploading ${file.name}…`);try{const xhr=new XMLHttpRequest();const result=await new Promise((resolve,reject)=>{xhr.open('POST',`/api/v1/documents/uploads?filename=${encodeURIComponent(file.name)}`);const key=localStorage.getItem('citebot.adminKey');if(key)xhr.setRequestHeader('X-Api-Key',key);xhr.onload=()=>xhr.status<300?resolve(JSON.parse(xhr.responseText)):reject(new Error(JSON.parse(xhr.responseText||'{}').detail||`Upload failed (${xhr.status})`));xhr.onerror=()=>reject(new Error('Upload connection failed'));xhr.send(file)});toast(`${file.name} ${result.job.status==='completed'?'is ready':'is processing'}`)}catch(error){toast(`${file.name}: ${error.message}`,true)}await refreshDocuments()}}
async function refreshConversations(){try{const rows=await api.request('/conversations',{headers:api.headers('research',false)});$('#conversationList').innerHTML=rows.map(r=>`<button class="conversation-item ${r.session_id===state.sessionId?'active':''}" data-session="${r.session_id}">${escapeHtml(r.title)}</button>`).join('');$$('.conversation-item').forEach(b=>b.onclick=()=>loadConversation(b.dataset.session))}catch(error){console.warn(error)}}
async function loadConversation(id){try{const record=await api.request(`/conversations/${id}`,{headers:api.headers('research',false)});state.sessionId=id;state.citations=[];$('#emptyChat').classList.add('hidden');$('#messages').innerHTML='';record.turns.forEach(turn=>appendMessage(turn.role,turn.content));refreshConversations();showView('chat')}catch(error){toast(error.message,true)}}
function newChat(){state.sessionId=null;state.citations=[];$('#messages').innerHTML='';$('#emptyChat').classList.remove('hidden');$('#sourcePanel').classList.remove('open');refreshConversations();$('#queryInput').focus()}
function appendMessage(role,content,citations=[],verification={}){$('#emptyChat').classList.add('hidden');const el=document.createElement('article');el.className=`message ${role}`;if(role==='assistant'){const cited=citations.length?`<div class="answer-meta"><span>${citations.length} source${citations.length===1?'':'s'}</span><span>Evidence checked</span><span>${escapeHtml((verification.answer_status||'draft').replaceAll('_',' '))}</span>${Number.isFinite(verification.evidence_coverage)?`<span>${Math.round(verification.evidence_coverage*100)}% claim coverage</span>`:''}${verification.contradiction_count?`<span>${verification.contradiction_count} contradiction${verification.contradiction_count===1?'':'s'}</span>`:''}</div>`:'';el.innerHTML=`<div class="message-label">CiteBot</div><p>${escapeHtml(content)} ${citations.map((c,i)=>`<button class="citation-button" data-citation="${i}">${i+1}</button>`).join('')}</p>${cited}`;el.querySelectorAll('.citation-button').forEach(b=>b.onclick=()=>inspectCitation(citations[Number(b.dataset.citation)]))}else el.innerHTML=`<p>${escapeHtml(content)}</p>`;$('#messages').append(el);el.scrollIntoView({behavior:'smooth',block:'end'});return el}
function inspectCitation(c){if(!c)return;$('#sourceEmpty').classList.add('hidden');$('#sourceContent').classList.remove('hidden');$('#sourceContent').innerHTML=`<h2 class="source-document">${escapeHtml(c.title)}</h2><div class="source-location">${escapeHtml(c.location_marker|| (c.page?`Page ${c.page}`:'Indexed source'))}</div><blockquote class="source-quote">${escapeHtml(c.quoted_support)}</blockquote><p class="source-support">${escapeHtml(c.support_span)}</p>`;$('#sourcePanel').classList.add('open')}
async function submitQuestion(query){if(state.busy)return;state.busy=true;$('#sendButton').disabled=true;appendMessage('user',query);const pending=appendMessage('assistant','Searching your library and checking sources…');pending.classList.add('pending');try{const response=await fetch('/api/v1/research/query/stream',{method:'POST',headers:api.headers('research'),body:JSON.stringify({session_id:state.sessionId,query,top_k:6})});if(!response.ok)throw new Error(`Chat request failed (${response.status})`);const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',completed=null;while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});const lines=buffer.split('\n');buffer=lines.pop();for(const line of lines){if(!line)continue;const event=JSON.parse(line);if(event.event==='start')state.sessionId=event.data.session_id;if(event.event==='complete')completed=event.data;if(event.event==='error')throw new Error(event.data.detail)}if(done)break}pending.remove();if(!completed)throw new Error('The research request ended without an answer');state.citations=completed.answer.citations||[];appendMessage('assistant',completed.answer.direct_answer,state.citations,completed);await refreshConversations()}catch(error){pending.remove();appendMessage('assistant',`I couldn't complete that request. ${error.message}`);toast(error.message,true)}finally{state.busy=false;$('#sendButton').disabled=false}}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));$('#newChatButton').onclick=newChat;$('#uploadButton').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>uploadFiles(e.target.files);$('#documentSearch').oninput=renderDocuments;$('.suggestion')&&$$('.suggestion').forEach(b=>b.onclick=()=>{showView('chat');$('#queryInput').value=b.textContent;submitQuestion(b.textContent)});$('#chatForm').onsubmit=e=>{e.preventDefault();const q=$('#queryInput').value.trim();if(q){$('#queryInput').value='';submitQuestion(q)}};$('#queryInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#chatForm').requestSubmit()}};$('#queryInput').oninput=e=>{e.target.style.height='auto';e.target.style.height=`${e.target.scrollHeight}px`};$('#closeSources').onclick=()=>$('#sourcePanel').classList.remove('open');
const dz=$('#dropZone');['dragenter','dragover'].forEach(n=>dz.addEventListener(n,e=>{e.preventDefault();dz.classList.add('dragging')}));['dragleave','drop'].forEach(n=>dz.addEventListener(n,e=>{e.preventDefault();dz.classList.remove('dragging')}));dz.ondrop=e=>uploadFiles(e.dataTransfer.files);dz.onclick=()=>$('#fileInput').click();
$('#settingsButton').onclick=()=>{ $('#researchKey').value=localStorage.getItem('citebot.researchKey')||'';$('#adminKey').value=localStorage.getItem('citebot.adminKey')||'';$('#settingsDialog').showModal()};$('#saveSettings').onclick=()=>{localStorage.setItem('citebot.researchKey',$('#researchKey').value);localStorage.setItem('citebot.adminKey',$('#adminKey').value);toast('Connection settings saved');setTimeout(()=>{refreshDocuments();refreshConversations()},0)};
refreshDocuments();refreshConversations();setInterval(()=>{if(!$('#documentsView').classList.contains('hidden'))refreshDocuments()},4000);
